/**
 * Help content registry — defines sections for each page's help drawer.
 * All values are i18n keys (not raw text).
 */
export const HELP_PAGES = {
    dashboard: {
        titleKey: 'help.dashboard.title',
        overviewKey: 'help.dashboard.overview',
        sections: [
            { titleKey: 'help.dashboard.stats.title', contentKey: 'help.dashboard.stats.content' },
            { titleKey: 'help.dashboard.filters.title', contentKey: 'help.dashboard.filters.content' },
            { titleKey: 'help.dashboard.export.title', contentKey: 'help.dashboard.export.content' },
            { titleKey: 'help.dashboard.export.steps', contentKey: 'help.dashboard.export.stepsContent' },
        ],
        tipsKey: 'help.dashboard.tips',
    },
    calls: {
        titleKey: 'help.calls.title',
        overviewKey: 'help.calls.overview',
        sections: [
            { titleKey: 'help.calls.table.title', contentKey: 'help.calls.table.content' },
            { titleKey: 'help.calls.filters.title', contentKey: 'help.calls.filters.content' },
            { titleKey: 'help.calls.filters.steps', contentKey: 'help.calls.filters.stepsContent' },
            { titleKey: 'help.calls.detail.title', contentKey: 'help.calls.detail.content' },
            { titleKey: 'help.calls.detail.steps', contentKey: 'help.calls.detail.stepsContent' },
            { titleKey: 'help.calls.quality.title', contentKey: 'help.calls.quality.content' },
            { titleKey: 'help.calls.import.title', contentKey: 'help.calls.import.content' },
            { titleKey: 'help.calls.import.steps', contentKey: 'help.calls.import.stepsContent' },
        ],
        tipsKey: 'help.calls.tips',
    },
    scenarios: {
        titleKey: 'help.scenarios.title',
        overviewKey: 'help.scenarios.overview',
        sections: [
            { titleKey: 'help.scenarios.templates.title', contentKey: 'help.scenarios.templates.content' },
            { titleKey: 'help.scenarios.templates.steps', contentKey: 'help.scenarios.templates.stepsContent' },
            { titleKey: 'help.scenarios.dialogues.title', contentKey: 'help.scenarios.dialogues.content' },
            { titleKey: 'help.scenarios.dialogues.steps', contentKey: 'help.scenarios.dialogues.stepsContent' },
            { titleKey: 'help.scenarios.safety.title', contentKey: 'help.scenarios.safety.content' },
            { titleKey: 'help.scenarios.safety.steps', contentKey: 'help.scenarios.safety.stepsContent' },
            { titleKey: 'help.scenarios.affects.title', contentKey: 'help.scenarios.affects.content' },
        ],
        tipsKey: 'help.scenarios.tips',
    },
    knowledge: {
        titleKey: 'help.knowledge.title',
        overviewKey: 'help.knowledge.overview',
        sections: [
            { titleKey: 'help.knowledge.articles.title', contentKey: 'help.knowledge.articles.content' },
            { titleKey: 'help.knowledge.articles.steps', contentKey: 'help.knowledge.articles.stepsContent' },
            { titleKey: 'help.knowledge.sources.title', contentKey: 'help.knowledge.sources.content' },
            { titleKey: 'help.knowledge.sources.steps', contentKey: 'help.knowledge.sources.stepsContent' },
            { titleKey: 'help.knowledge.scraper.title', contentKey: 'help.knowledge.scraper.content' },
            { titleKey: 'help.knowledge.watched.title', contentKey: 'help.knowledge.watched.content' },
            { titleKey: 'help.knowledge.watched.steps', contentKey: 'help.knowledge.watched.stepsContent' },
            { titleKey: 'help.knowledge.promotions.title', contentKey: 'help.knowledge.promotions.content' },
            { titleKey: 'help.knowledge.promotions.steps', contentKey: 'help.knowledge.promotions.stepsContent' },
            { titleKey: 'help.knowledge.affects.title', contentKey: 'help.knowledge.affects.content' },
        ],
        tipsKey: 'help.knowledge.tips',
    },
    prompts: {
        titleKey: 'help.prompts.title',
        overviewKey: 'help.prompts.overview',
        sections: [
            { titleKey: 'help.prompts.versions.title', contentKey: 'help.prompts.versions.content' },
            { titleKey: 'help.prompts.versions.steps', contentKey: 'help.prompts.versions.stepsContent' },
            { titleKey: 'help.prompts.ab.title', contentKey: 'help.prompts.ab.content' },
            { titleKey: 'help.prompts.ab.steps', contentKey: 'help.prompts.ab.stepsContent' },
            { titleKey: 'help.prompts.affects.title', contentKey: 'help.prompts.affects.content' },
        ],
        tipsKey: 'help.prompts.tips',
    },
    sandbox: {
        titleKey: 'help.sandbox.title',
        overviewKey: 'help.sandbox.overview',
        sections: [
            { titleKey: 'help.sandbox.chat.title', contentKey: 'help.sandbox.chat.content' },
            { titleKey: 'help.sandbox.chat.steps', contentKey: 'help.sandbox.chat.stepsContent' },
            { titleKey: 'help.sandbox.regression.title', contentKey: 'help.sandbox.regression.content' },
            { titleKey: 'help.sandbox.regression.steps', contentKey: 'help.sandbox.regression.stepsContent' },
            { titleKey: 'help.sandbox.patterns.title', contentKey: 'help.sandbox.patterns.content' },
            { titleKey: 'help.sandbox.phrases.title', contentKey: 'help.sandbox.phrases.content' },
            { titleKey: 'help.sandbox.starters.title', contentKey: 'help.sandbox.starters.content' },
            { titleKey: 'help.sandbox.import.title', contentKey: 'help.sandbox.import.content' },
            { titleKey: 'help.sandbox.import.steps', contentKey: 'help.sandbox.import.stepsContent' },
            { titleKey: 'help.sandbox.workflow.title', contentKey: 'help.sandbox.workflow.content' },
        ],
        tipsKey: 'help.sandbox.tips',
    },
    operators: {
        titleKey: 'help.operators.title',
        overviewKey: 'help.operators.overview',
        sections: [
            { titleKey: 'help.operators.table.title', contentKey: 'help.operators.table.content' },
            { titleKey: 'help.operators.creating.title', contentKey: 'help.operators.creating.content' },
            { titleKey: 'help.operators.creating.steps', contentKey: 'help.operators.creating.stepsContent' },
            { titleKey: 'help.operators.status.title', contentKey: 'help.operators.status.content' },
            { titleKey: 'help.operators.status.steps', contentKey: 'help.operators.status.stepsContent' },
            { titleKey: 'help.operators.skills.title', contentKey: 'help.operators.skills.content' },
            { titleKey: 'help.operators.transfer.title', contentKey: 'help.operators.transfer.content' },
            { titleKey: 'help.operators.affects.title', contentKey: 'help.operators.affects.content' },
        ],
        tipsKey: 'help.operators.tips',
    },
    monitoring: {
        titleKey: 'help.monitoring.title',
        overviewKey: 'help.monitoring.overview',
        sections: [
            { titleKey: 'help.monitoring.health.title', contentKey: 'help.monitoring.health.content' },
            { titleKey: 'help.monitoring.extended.title', contentKey: 'help.monitoring.extended.content' },
            { titleKey: 'help.monitoring.external.title', contentKey: 'help.monitoring.external.content' },
        ],
        tipsKey: 'help.monitoring.tips',
    },
    configuration: {
        titleKey: 'help.configuration.title',
        overviewKey: 'help.configuration.overview',
        sections: [
            { titleKey: 'help.configuration.reload.title', contentKey: 'help.configuration.reload.content' },
            { titleKey: 'help.configuration.llm.title', contentKey: 'help.configuration.llm.content' },
            { titleKey: 'help.configuration.llm.steps', contentKey: 'help.configuration.llm.stepsContent' },
            { titleKey: 'help.configuration.tasks.title', contentKey: 'help.configuration.tasks.content' },
            { titleKey: 'help.configuration.affects.title', contentKey: 'help.configuration.affects.content' },
        ],
        tipsKey: 'help.configuration.tips',
    },
    notifications: {
        titleKey: 'help.notifications.title',
        overviewKey: 'help.notifications.overview',
        sections: [
            { titleKey: 'help.notifications.telegram.title', contentKey: 'help.notifications.telegram.content' },
            { titleKey: 'help.notifications.telegram.steps', contentKey: 'help.notifications.telegram.stepsContent' },
            { titleKey: 'help.notifications.affects.title', contentKey: 'help.notifications.affects.content' },
        ],
        tipsKey: 'help.notifications.tips',
    },
    tenants: {
        titleKey: 'help.tenants.title',
        overviewKey: 'help.tenants.overview',
        sections: [
            { titleKey: 'help.tenants.table.title', contentKey: 'help.tenants.table.content' },
            { titleKey: 'help.tenants.creating.title', contentKey: 'help.tenants.creating.content' },
            { titleKey: 'help.tenants.creating.steps', contentKey: 'help.tenants.creating.stepsContent' },
            { titleKey: 'help.tenants.tools.title', contentKey: 'help.tenants.tools.content' },
            { titleKey: 'help.tenants.affects.title', contentKey: 'help.tenants.affects.content' },
        ],
        tipsKey: 'help.tenants.tips',
    },
    users: {
        titleKey: 'help.users.title',
        overviewKey: 'help.users.overview',
        sections: [
            { titleKey: 'help.users.table.title', contentKey: 'help.users.table.content' },
            { titleKey: 'help.users.creating.title', contentKey: 'help.users.creating.content' },
            { titleKey: 'help.users.creating.steps', contentKey: 'help.users.creating.stepsContent' },
            { titleKey: 'help.users.roles.title', contentKey: 'help.users.roles.content' },
            { titleKey: 'help.users.permissions.title', contentKey: 'help.users.permissions.content' },
            { titleKey: 'help.users.permissions.groups.title', contentKey: 'help.users.permissions.groups.content' },
            { titleKey: 'help.users.permissions.steps', contentKey: 'help.users.permissions.stepsContent' },
        ],
        tipsKey: 'help.users.tips',
    },
    audit: {
        titleKey: 'help.audit.title',
        overviewKey: 'help.audit.overview',
        sections: [
            { titleKey: 'help.audit.table.title', contentKey: 'help.audit.table.content' },
            { titleKey: 'help.audit.filters.title', contentKey: 'help.audit.filters.content' },
            { titleKey: 'help.audit.filters.steps', contentKey: 'help.audit.filters.stepsContent' },
        ],
        tipsKey: 'help.audit.tips',
    },
    vehicles: {
        titleKey: 'help.vehicles.title',
        overviewKey: 'help.vehicles.overview',
        sections: [
            { titleKey: 'help.vehicles.navigation.title', contentKey: 'help.vehicles.navigation.content' },
            { titleKey: 'help.vehicles.navigation.steps', contentKey: 'help.vehicles.navigation.stepsContent' },
            { titleKey: 'help.vehicles.import.title', contentKey: 'help.vehicles.import.content' },
            { titleKey: 'help.vehicles.import.steps', contentKey: 'help.vehicles.import.stepsContent' },
            { titleKey: 'help.vehicles.affects.title', contentKey: 'help.vehicles.affects.content' },
        ],
        tipsKey: 'help.vehicles.tips',
    },
    tools: {
        titleKey: 'help.tools.title',
        overviewKey: 'help.tools.overview',
        sections: [
            { titleKey: 'help.tools.overrides.title', contentKey: 'help.tools.overrides.content' },
            { titleKey: 'help.tools.overrides.steps', contentKey: 'help.tools.overrides.stepsContent' },
            { titleKey: 'help.tools.list.title', contentKey: 'help.tools.list.content' },
            { titleKey: 'help.tools.affects.title', contentKey: 'help.tools.affects.content' },
        ],
        tipsKey: 'help.tools.tips',
    },
};
